### ISSUE TITLE
"Contribution" - Formal Definition

### ISSUE THREAD

**Issue by jasnell** [jasnell/dev-policy#1]
We'll likely need a formal definition of a "Contribution" at some point... e.g.: https://www.apache.org/licenses/icla.txt 

"Contribution" shall mean any original work of authorship,
including any modifications or additions to an existing work, that
is intentionally submitted by You to the Foundation for inclusion
in, or documentation of, any of the products owned or managed by
the Foundation (the "Work"). For the purposes of this definition,
"submitted" means any form of electronic, verbal, or written
communication sent to the Foundation or its representatives,
including but not limited to communication on electronic mailing
lists, source code control systems, and issue tracking systems that
are managed by, or on behalf of, the Foundation for the purpose of
discussing and improving the Work, but excluding communication that
is conspicuously marked or otherwise designated in writing by You
as "Not a Contribution."

**Comment by a0viedo** [comment]
+1. @jasnell did you had any actionable item in mind for this or this is no longer relevant?

**Comment by jasnell** [comment]
This is no longer relevant. This repo can actually be archived.
