### ISSUE TITLE
Reconcile with https://nodejs.org/documentation/workflow/

### ISSUE THREAD

**Issue by jasnell** [jasnell/dev-policy#10]
Need to determine where the current draft dev policy differs from https://nodejs.org/documentation/workflow/ and which parts from that document either (a) still need to be captured or (b) become obsolete under the converged approach.

**Comment by Fishrock123** [comment]
Isn't this a dupe of ~~both #8 and~~ #9..?

Nope, just #9, my bad.

**Comment by jasnell** [comment]
Somewhat... this is largely a placeholder issue for me. I need to get back in and go through the doc in detail to make sure. If the issues are already covered by 8 and 9 I'll close this, otherwise I'll update it with the additional points that still need to be addressed.
