### ISSUE TITLE
"Ownership and transfer" comments

### ISSUE THREAD

**Issue by zxcvnull** [jasnell/dev-policy#12]
Hi all,

A minor comment/observation:

> Upon Foundation launch, both projects will come together under a single TSC...
> 
> ...For the Converged Project, a new Github organization owned and managed by the Node.js Foundation will be created. Once the new Github organization is established, ownership of the existing iojs/io.js and joyent/node repositories should be transferred.

What this also means is that barring any side agreements, the Foundation effectively “captures” both projects. Neither may henceforth be extracted. In the long term, _this is probably a good thing._

Forks remain possible, but any such fork (even by the _entire_ set of Collaborators acting in concert) have to be to as a completely new project (and specifically not as io.js or node.js). Again, in the long term, _this is probably a good thing._

Nonetheless, I refer briefly to the notable volume of community concern regarding this proposal in the io.js camp and would propose a simple but effective mechanism by which to defuse many of the current community concerns:

> Provide a limited time window (6-12 months) deferral of transfer and/or a “majority TC” transfer mechanism.

A clause to either/both:
- **Deferral of transfer** - transfer ownership after "some period" with the ability _within_ that period for the majority of the TCs of either project to submit withdrawal from the agreement.
- **Majority TC transfer** - providing a means by which the majority of the TCs of either project (as they are defined today) may request to withdraw their project and return ownership of the repository AND brandnames, within “some period” of the Converged Project commencement.

This would defuse concerns of either project being “hijacked”, and remove any potential for either side to dominate the Foundation (at least for the honeymoon period to be defined).

This is consistent with the Consensus Seeking Model, does not change the roadmap or the intent of the deal, and provides a powerful trump card to _both_ sides to keep it honest. If there's a good reason _not_ to do this, it'd be great to explain _why_ that is to the community.

This is a lawyer-type thought experiment only, and is offered with constructive intentions in the spirit of wanting this project to succeed.

**Comment by mikeal** [comment]
So... there's a bit of a loophole here. There is no io.js trademark because io.js has no institution and no money :)

That means that the foundation doesn't actually get the trademark (because it doesn't exist) and that, theoretically, anyone could fork it again and call it io.js (although Fedor owns the domain name so in reality they would probably need him).

**Comment by zxcvnull** [comment]
Kind of. I think if io.js was able to get legal advice on the trademark matter, the reality would be a (hopefully) pleasant surprise.

I suspect you’d find that a de facto Trademark **does exist**, even if it is not registered and its de jure ownership is not exactly/clearly defined in this case (if pressed in court, for instance). It has value and its ownership would arguably (in the legal sense) be transferred on transfer of the io.js Github organisation to the Node Foundation under a charter that is talking about ‘ownership’ of repositories (and by arguable extension, assets).

Critically, it is _far from clear_ that the ‘io.js’ name would ever be able to be used by someone other than the Foundation from that point on (including the original io.js founding/forking team).

Either way, I’d humbly submit to include a "breakup clause" that unambiguously outlines unspoken assumptions such as “gets to use the io.js name” etc. and the terms under which a breakup would be triggered. 

When it comes to “what if it goes bad": **Assume that anything not clearly written down is _off the table_.**

And on this point, the other side of the coin is putting in sensible conditions. You don’t want 2 former TCs and a loudmouth collaborator backing out of the project 3 years from now to re-spin io.js because they don't like the flavour of the donuts anymore. A simple majority within a reasonable timeframe to “Declare or hold peace”.

This is all “worst case” crap that no-one really likes talking about, but especially for the io.js side (who are not being legally represented) it’s essential to put this stuff on the table - even if it’s just for the TC to say “this doesn’t matter”.

**Comment by mikeal** [comment]
> I suspect you’d find that a de facto Trademark does exist

If it does exist it belongs to Fedor. We should just makes sure that Fedor retains ownership of any "io.js" assets.
