### ISSUE TITLE
Should semver-major PR's always require TSC review?

### ISSUE THREAD

**Issue by jasnell** [jasnell/dev-policy#14]
An argument can be made that any change that requires a semver-major bump ought to be put on the TSC agenda as a sanity check. These ought to be rare and likely are far reaching in impact so requiring the additional review would make sense.

/cc @mikeal

**Comment by Fishrock123** [comment]
I'm not so sure about them being quite that rare, but this seems like an ok idea.

**Comment by Fishrock123** [comment]
Also not that v8 x.0.0.0 or 0.x.0.0 updates can also be semver-major (iirc, usually are).

**Comment by mhdawson** [comment]
I'd agree that we want TSC input on any breaking change
