### ISSUE TITLE
Review other projects contribution guidelines for inspiration

### ISSUE THREAD

**Issue by jasnell** [jasnell/dev-policy#15]
Is there anything we'd want to steal... err... adopt from other projects...

docker - https://github.com/docker/docker/blob/master/CONTRIBUTING.md
openstack - https://wiki.openstack.org/wiki/How_To_Contribute

**Comment by Fishrock123** [comment]
rust - https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md

**Comment by mikeal** [comment]
https://docs.djangoproject.com/en/dev/internals/contributing/

**Comment by jasnell** [comment]
OpenStack Developers Guide: http://docs.openstack.org/infra/manual/developers.html
OpenStack Branch Model: https://wiki.openstack.org/wiki/Branch_Model
OpenStack Blueprints: https://wiki.openstack.org/wiki/Blueprints
NVIE Branching Model: http://nvie.com/posts/a-successful-git-branching-model/
Igor Branching Model: https://igor.io/2013/10/21/git-branching-model.html
Rust - Stability as a Deliverable: http://blog.rust-lang.org/2014/10/30/Stability.html
Django Roadmap: https://code.djangoproject.com/wiki/Version1.8Roadmap
Docker Roadmap: https://github.com/docker/docker/blob/master/project/ROADMAP.md
(intentionally looking at alternative models to compare...)
