### ISSUE TITLE
Does the Code of Conduct belong here?

### ISSUE THREAD

**Issue by Fishrock123** [jasnell/dev-policy#16]
/cc @mikeal

**Comment by jasnell** [comment]
I believe the Code of Conduct will be handled separately as part of the TSC Policy document. What is expected is that the TSC will adopt a generalized code of conduct and that Working Groups will be allowed to extend it as necessary.

**Comment by Fishrock123** [comment]
> I believe the Code of Conduct will be handled separately as part of the TSC Policy document.

Ok, close if that is the case.

> Working Groups will be allowed to extend it as necessary.

I don't understand why that would ever be the case?

**Comment by jasnell** [comment]
International legal and cultural differences may require specific WG's (particularly the i18n WG and subteams) to vary the policy somewhat. The idea would be that only additive changes would be permitted.

**Comment by jasnell** [comment]
I'll keep the issue open for now until we get confirmation.

**Comment by mikeal** [comment]
Ya, the TSC has a CoC which the project inherits and we are instructing each WG to start with that CoC and make modifications as they see fit.
