### ISSUE TITLE
A few comments

### ISSUE THREAD

**Issue by mhdawson** [jasnell/dev-policy#19]
I've not read all the comments yet so there may be some overlap:

1) minor nit
The semver-minor and semver-major tags are used for Rull Requests that will cause a version iteration other than patch once released.

Type Rull --> Pull

2) In the discussion on declaring LTS candidate the wording that indicates "Major version increased to 2.0.0." might be better as "New branch created from master with new major version ex: 2.0.0" so that its clear what the origin is for each new branch.

**Comment by jasnell** [comment]
for #2, that's not quite the step. The current working version in _master_ could be set to 2.0.0 when the LTS WG declares that there will be a LTS release in the 2.x line. At that point, the LTS WG may create a Milestone targeting a specific upcoming minor version targeted at being the LTS release. The branch for that may not yet have been created. Once the LTS WG is satisfied that the LTS release target is ready to go, then the branches are cut. Things will get tagged along the way, but actual release branches themselves may not yet have been created.

**Comment by mhdawson** [comment]
Maybe its "Master tagged with new major version ex: 2.0.0" just want to be clear what the source is.

**Comment by jasnell** [comment]
@mdawsonibm can you check the latest version of the draft and see if that resolves your second comment.
