### ISSUE TITLE
review-required tag

### ISSUE THREAD

**Issue by jasnell** [jasnell/dev-policy#2]
The _review-required_ tag is a suggested addition.. from the google doc notes:

@jasnell: what do you think? Not everything needs to be elevated the tsc-agenda. Some things should be elevated to a WG level review.
@mikeal: when used with the tsc-agenda tag it's kind of redundant but I can see this being quite useful when escalating to a WG.
@jasnell: Yes, there is some redundancy but given that the WG tags may vary quite a bit, this gives us a singular way of marking review-required issues regardless of where the decision needs to be made.

**Comment by Fishrock123** [comment]
See:
https://github.com/jasnell/dev-policy/commit/7ef8763d26d023419f899f875c100420bcd6e9cb#commitcomment-10571511
https://github.com/jasnell/dev-policy/commit/7ef8763d26d023419f899f875c100420bcd6e9cb#commitcomment-10571518

it's easier to just cc an @org/group

**Comment by jasnell** [comment]
Agreed that it's easier to cc the @org/group to review but there should be some level of guarantee that the issue or PR will not be acted upon until there's been enough time to review the issue and allow the WG or TSC to come to a decision.

**Comment by Fishrock123** [comment]
I'm more ok with specific tags for WGs, i.e. `tc-agenda` works well.

However, this plays into that the issue should not be contentious among collaborators when merging. I.e., I am less than sure that the tag should be used as a "guarantee".
