### ISSUE TITLE
To NAN or not to NAN

### ISSUE THREAD

**Issue by mikeal** [jasnell/dev-policy#31]
Logging an issue around the last line in this latest change for the agenda today:

https://github.com/jasnell/dev-policy/pull/29

**Comment by Fishrock123** [comment]
So two points:
1. We need native abstractions because underlying code in practice changes too often.
2. A lot of people use NAN, making something entirely new would probably be painful.

**Comment by misterdjules** [comment]
I think the point of the changes in #29  was to not "hardcode" any specific implementation for an abstraction layer between Node.js and V8 into the development policy.

Why would the development policy include implementation details that have no significant impact on the development workflow of Node.js' core itself? If NAN is adopted in the merged project, do we want to have to change the whole TSC development policy to move to NAN 2.0, or whatever the evolution of NAN leads to?

It seems to me that the work around the abstraction layer between Node.js and V8 should take place in a separate working group, maybe some sort of Node.js API working group.

**Comment by jasnell** [comment]
Keep in mind that, at this point, nothing is "hard coded" in the document. At this point the entire thing is up for discussion. But it is a fair point. Keep in mind, however, that there are plenty of implementation bits discussed in the document already (v8 and npm dependencies, for instance). There's a correct balance to be reached here somewhere. 

An API WG would likely be a very good thing.

**Comment by mikeal** [comment]
The NAN WG I believe is already chartered with more than just the development and maintinence of the `nan` module but also in continuing to improve and provide native abstractions.

**Comment by geek0x23** [comment]
I (and my employer) have a huge interest in the binary addon story for Node.js.  What's the best way to involve myself in this working group?  For example, I'm a huge fan of https://github.com/tjfontaine/node-addon-layer , and I'd love to see Node embrace a C api, rather than a C++ one.

**Comment by Fishrock123** [comment]
@swaj probably take a look at https://github.com/nodejs/nan/issues/373 / https://github.com/nodejs/nan/issues

The Natives WG hasn't officially launched per-say, and I don't think they've had a meeting yet.
