### ISSUE TITLE
How development branches are used

### ISSUE THREAD

**Issue by mhdawson** [jasnell/dev-policy#32]
The document calls out development branches but we have not set the expectations of when a development branch should be used versus delivering directly to Master.

I'd suggest we expand the existing line "The master branch must always be in a production-ready state. Features landed must be complete and functional." to be: 

The master branch must always be in a production-ready state. Features landed must be complete and functional.  For features that are complex, change a large number of files or where they may be differing opinions on the best way to proceed it is expected that development will be done in development branches until the point where the feature is fully complete, all tests are written and passing, and consensus has been achieved in respect to the implementation choices.

**Comment by Fishrock123** [comment]
>  For features that are complex, change a large number of files or where they may be differing opinions on the best way to proceed it is expected that development will be done in development branches until the point where the feature is fully complete, all tests are written and passing, and consensus has been achieved in respect to the implementation choices.

I disagree that changes that are "complex" or touch a large number of files **must** be done in a dev branch if the changeset is already complete and tests are passing on CI.

**Comment by jasnell** [comment]
The main idea is that master ought to be production ready so changesets going in need to represent "complete thoughts" as opposed to partially done work. A "development branch" doesn't need to be a formal thing -- that is, it could be someone's working fork they use for development and sending the PR along. I _believe_ (correct me if I'm wrong @Fishrock123) that lines up with what you mean by "already complete and tests are passing on CI"

**Comment by Fishrock123** [comment]
Right, but I don't think that is how we are currently using our language of "Development Branches".

I.e. having a `v8-next` branch in core.

Also, where does that put PR's like this? https://github.com/iojs/io.js/pull/1325

The changes themselves are useful/complete, but the pr isn't necessarily a "complete thought". (it's all run-up to OpenSSL 1.0.2)

**Comment by jasnell** [comment]
I do not have answers to those questions yet :-)

**Comment by jasnell** [comment]
For something like https://github.com/iojs/io.js/pull/1325, the decision could likely be based on 1. Is the changeset complete? 2. Is it capable of standing alone without additional commits to make it work? 3. Does it pass all the tests? For Question 2, it might need additional commits later on to make it completely _useful_ but landing the commit itself would not break anything if we happened to cut an LTS before the rest of it came along later.

**Comment by jasnell** [comment]
Related: #26

**Comment by mhdawson** [comment]
Jame's comment above reflects what I was trying to convey.  The work needs to be done outside of master until it meets the requirements stated.  Since there seems to be some existing concept of what a "development" branch is we might want to add this to the doc and then change the terminology used in my original suggestion.  For example ,I've heard mentioned that the might be a canary branch which could be one of the per-defined development branches were work "could" be, but not necessarily, be carried out before it goes into master.

**Comment by Fishrock123** [comment]
Ok, yeah, the wording is kind of funny. The work needs to be done outside of master, but not in a "development" release branch.

**Comment by jasnell** [comment]
I've wanted to avoid putting any kind of definition on "development branch" because all it's really intended to mean is "outside of master". I can work on the wording around this bit tho.

**Comment by orangemocha** [comment]
"Feature branches" might be more appropriate wording.
