### ISSUE TITLE
Rechartering existing io.js Working Groups

### ISSUE THREAD

**Issue by jasnell** [jasnell/dev-policy#34]
The discussion around #31 (nan) brings up the possibility that existing io.js WGs brought under the Foundation TC may need to be slightly or significantly rechartered once the combined TSC is formed. At the very least, the possibility of re-reviewing the charters needs to be put on the table.

**Comment by mikeal** [comment]
The next steps in my Lifecycle PR is to look through all the working groups and see where they fit and how they can move over.

Most WGs aren't that close to core and can move over quite easily but some may need to altered re-scoped.
