### ISSUE TITLE
Reconciling CI

### ISSUE THREAD

**Issue by mikeal** [jasnell/dev-policy#35]
We should tackle this _after_ the meeting today but I wanted an issue open so that we could point people at it during the meeting.

io.js and node.js both have CI infrastructure and a variety of features that we'll need to reconcile together in a merged project.

**Comment by orangemocha** [comment]
+1

There might also be some logistic considerations in that the current hardware resources might not scale to handle the increased volume of commits and number of branches resulting from a merged project.

I am not sure if this fits into dev policy, but it's good to point out that work will need to be done in this area, and we can at least identify which WG will be chartered with this task.

**Comment by Fishrock123** [comment]
The resources in the io.js CI are generally enough to handle CI runs on all non-doc PR's pre-merge. Maybe with the exception of certain ARM platforms such as the Raspberry PI 1.

**Comment by mikeal** [comment]
Does anyone know the differences between what we do in CI for build/test compared to what node.js does? Maybe @cjihrig or @chrisdickinson

**Comment by Fishrock123** [comment]
cc @rvagg

**Comment by cjihrig** [comment]
[This](https://nodejs.org/documentation/workflow/#index_md_using_jenkins_to_build_test_and_merge_every_pr) explains the process on node.js. The biggest difference from a collaborator's point of view is that the node.js Jenkins job should perform the merge for you.

If you're asking about the Jenkins implementation details, then a conversation between @misterdjules and @rvagg would be invaluable.
