### ISSUE TITLE
On considering PRs by non-collaborators

### ISSUE THREAD

**Issue by orangemocha** [jasnell/dev-policy#38]
> All Pull Requests submitted by individuals who are not Collaborators must be signed-off on by an existing Collaborator before the PR will be considered.

Should these PRs really require to be "signed-off" before even being "considered"? That seems like an unnecessary step. Perhaps you need to clarify what "signed-off" entails. Is "nominated" or "sponsored" more appropriate?

**Comment by mikeal** [comment]
I would change "will be considered" to "can be merged."

**Comment by jasnell** [comment]
+1.. yeah, "considered" is just an unfortunate choice of words.
