### ISSUE TITLE
On requiring test cases for all bug fixes

### ISSUE THREAD

**Issue by orangemocha** [jasnell/dev-policy#40]
> All Pull Requests that either fix bugs or introduce new functionality require at least one test case demonstrating the defect or validating the intended functionality. For bug fixes, the test should fail before the change, and pass after the change.

In some cases, this might be a difficult task / the test case might be too large to fit into a unit test. We should leave some flexibility in this policy and clarify when a bug fix can be taken without a test case.

**Comment by srl295** [comment]
@orangemocha glad I hit reload before filing a dup.  :+1:
Perhaps something such as:

> In exceptional cases, such as environments or failure modes difficult to reproduce, a detailed testing
> description may be accepted in lieu of a specific test.

**Comment by Fishrock123** [comment]
Here's an example, for posterity: https://github.com/iojs/io.js/commit/c9207f7fc24d6ab879561632ba3c08fee07a9cc4

**Comment by orangemocha** [comment]
Memory leaks are another good example.
