### ISSUE TITLE
Convergence Working Group Nominations

### ISSUE THREAD

**Issue by jasnell** [jasnell/dev-policy#43]
Assuming we move forward with the Convergence WG... who should the members be? (we need nominations for trusted individuals from each Project TC) Post the nominations here and we'll get the list compiled for the next call.

**Comment by mikeal** [comment]
I'd like to be involved so that I can help deal with converging the WGs and GitHub org but I'll probably stay out of code convergence stuff.

On the code convergence side I'd like to nominate Chris Dickinson and Jeremiah Senkpiel and my guess is that Bert will also want to be on.

**Comment by Fishrock123** [comment]
I'm ok with this so long as there are other even more technical people like chris and bert involved. :)

**Comment by mhdawson** [comment]
I'd like to be involved in this.

**Comment by jasnell** [comment]
I'll add my name to the list as well.
