### ISSUE TITLE
Action items for 2015-04-13 Meeting

### ISSUE THREAD

**Issue by jasnell** [jasnell/dev-policy#55]
Action items from todays call:
1. Doodle Poll for regular joint TC meetings (@jasnell)
2. Doodle Poll for reddit AMA Q/A session (Mike Dolan)
3. Draft blog post / article describing foundation and TC processes (@jasnell, Mike Dolan, others)
4. Ensure current dev-policy and TSC charter drafts are appropriately addressing io.js community concerns, propose necessary iterations (@mikeal)

**Comment by Fishrock123** [comment]
@mikeal were you the one who had the recording?

Also, do we have notes? I was doing some other stuff and forgot to check.

**Comment by mikeal** [comment]
I have the recording, I'm just struggling to get youtube to accept it. I'll mess around with converting it until it works.
