### ISSUE TITLE
Collecting LTS Requirements from the User Community

### ISSUE THREAD

**Issue by jasnell** [jasnell/dev-policy#67]
This issue is a placeholder for discussion of LTS requirements from the broader user community.
1. What is a reasonable LTS release schedule? (2 per year, 1 per year, 1 per month, etc)
2. What is a reasonable LTS support timeframe (6 months, 1 year, 5 years, etc)
3. What is a reasonable LTS maintenance policy (fixes only, etc)
4. Is there anything in the proposed dev-policy that raises red flags as far as LTS support is concerned?
5. What's missing / What haven't we thought about yet ?

**Comment by shammond2000** [comment]
@jasnell Might be good to understand the expectations on stability and backward compatibility.  Similar for documenting the tests to be run before declaring the release is "ready."

**Comment by aredridel** [comment]
I like what's written; it does leave a lot open for future definition, however.

point 3 above is the one that really needs clarifying. I'd love to see features brought into LTS releases, especially after being vetted in the mainline and the implications for the community more fully understood. Keeping API and maybe even ABI compatibility over LTS releases would be wonderful. These constraints work against each other, but I think might be the sweet spot for uses I see every day. Enterprise developers want the new shiny features, but at the end of the day, they need to be vetted a bit first.

**Comment by totherik** [comment]
Thanks, @jasnell. As @aredridel mentioned, on our side we would like a cadence and maintenance policy that would allow us access to features. For us, _the actual cadence is less important than having one in the first place_. Observing that the release schedule of the main branch is expected to accelerate, the developer in me favors a schedule as frequent as quarterly releases, while the realist acknowledges twice per year would be sufficient and predictable for teams who are focused on delivering product.

I suppose it may be relevant to ask how _many_ LTS releases we expect the LTS WG/community could/should support per the maintenance policy. 

Also, does the LTS release also ship with npm, and if so, does the policy extend to cover npm fixes?

**Comment by Fishrock123** [comment]
> Also, does the LTS release also ship with npm, and if so, does the policy extend to cover npm fixes?

I think it should. io.js 1.8.2 (maintenance) will definitely include an even newer npm.

**Comment by mikeal** [comment]
> I think it should. io.js 1.8.2 (maintenance) will definitely include an even newer npm.

Yup, but likely won't ever take npm 3.0 in a 1.x line because it's a breaking change release.

**Comment by chrisdickinson** [comment]
@mikeal I wonder if we should "never say never" with regards to npm – I'm thinking about the problems caused by the introduction of `^` in semver ranges, when old versions of npm didn't support the syntax.

**Comment by mikeal** [comment]
@chrisdickinson in that case we'd want to backport support for ^ to the prior npm release line rather than update an old node.js line to a breaking release of npm.

**Comment by Fishrock123** [comment]
> in that case we'd want to backport support for ^ to the prior npm release line rather than update an old node.js line to a breaking release of npm.

That is definitely non-trivial as I recall from the node 0.8 situation and @isaacs' PRs to it.

**Comment by mikeal** [comment]
From what I can remember the issue there was that node.js didn't want to update npm for _any_ reason in an older release line. Supporting that new syntax would have been a feature addition, not a breaking change, and could have been done in an older line if that's what it would have taken for it to go in. Also, there has never really been a breaking changeset in npm the size of what is happening for 3.

**Comment by jasnell** [comment]
Close in favor of moving discussion to LTS repo --> https://github.com/nodejs/LTS/issues/8
