### ISSUE TITLE
Vague statement under conditions for landing pull request

### ISSUE THREAD

**Issue by aredridel** [jasnell/dev-policy#69]
"Verify that every commit passes all tests."

Each landed pull request commit, or each commit in succession within a pull request?

**Comment by Fishrock123** [comment]
Should be every commit (usually).

The idea is to have `master` as stable as possible at any one point. Tests should be added with fixes, in the same commits.

**Comment by Fishrock123** [comment]
That being said, I don't think the CI / tests **need** to be run against each commit in a PR, but each commit should aim to be a "complete" thought/statement in and of itself. (again, including tests in the same commits as fixes, etc.)

Perhaps this should be clarified more..

**Comment by aredridel** [comment]
I tend to agree, about quality of commits and each forming coherent changes and being testable. I think clarifying is useful there!

**Comment by jasnell** [comment]
Ok, will look at adding some clarification on this on Monday!

**Comment by aredridel** [comment]
Looks like this fell off the radar.
