### ISSUE TITLE
Do we need to include anything about the WGs in this doc?

### ISSUE THREAD

**Issue by jasnell** [jasnell/dev-policy#7]
https://github.com/iojs/io.js/blob/v1.x/WORKING_GROUPS.md

**Comment by mikeal** [comment]
WGs are free to adopt their own dev policies. Most of them differ strongly from how core operates.

**Comment by jasnell** [comment]
Yes, but it's likely worthwhile to make that explicit so there are no
surprises for anyone.

**Comment by Fishrock123** [comment]
Maybe just have them outline their dev policies?

**Comment by jasnell** [comment]
I was thinking something as simple as "Note that Working Groups are free to adopt their own specific development policies." :+1:  There's no need to make it any more complicated than that.
