### ISSUE TITLE
Why even attempt to merge io.js website?

### ISSUE THREAD

**Issue by RnbWd** [jasnell/dev-policy#70]
1) Please don't. 

2) How is that even possible?

3) For the foreseeable future it will be the source of io.js repositories

4) Even after the merge happens (probably in v.4.x or v5.x realistically), the website should still exist for stability of old releases, it wouldn't make sense to merge it with nodejs website

5) Io.js could theoretically rebrand itself as a sub-community within node that is working on master, aka the _experimental branch_, but IMO io.js is significantly more appealing of a name than _experimental_. The entire semver minor, master branch being _experimental_ should be removed from all future collaboration if it hasn't already.

$.002

**Comment by mikeal** [comment]
The staging of all this will be up to the website working group. The way that this will shake out is that the Website WG will move to the foundation and, at some point in the future, the domain name and other related assets will be available for the Website WG to manage. It'll be up to them how they want to stage any merges or migrations.

**Comment by RnbWd** [comment]
The issue is premature at the moment. When / if something happens, discussion should occur in WD itself. I'd like to share a few thoughts before closing.

It's important to preserve io.js as symbol. There's an historical precedent to be remembered, and if the foundation tries to bury the logo and pretend like the fork never happened...  I'd be very sad :(

I didn't think much of io.js until I saw  the [logos](https://github.com/iojs/io.js/issues/37). The symbol of io.js is deeply rooted in art, and that is significant. From Frederick Turner's [Art Recentered A Manifesto](http://frederickturnerpoet.com/?page_id=99):

> Art should grow from and speak to the common roots and universal principles of human nature in all cultures.
> Art should deny the simplifications of the political left and right, and should refine and deepen the radical center.
> Beauty [Art] is the opposite of coercive political power.
> Art is how a whole culture speaks to itself.
> Art is how cultures communicate with and marry each other.
> Art is the natural ally, interpreter, and guide of the sciences.
> The reflectiveness of art can be partly understood through the study of nonlinear dynamical systems and their strange attractors in nature and mathematics.
> Cultural evolution was partly driven by inventive play in artistic handicrafts and performance.
> Art looks with hope to the future and seeks a closer union with the true progress of technology.

Please do not let the symbol of io.js die in the process...

**Comment by mikeal** [comment]
FTR, after we vote on joining the foundation, assuming it's a yes vote, we will still be doing io.js releases until the code merge work is complete. After that, once all the releases are "node.js" and the other working groups have migrated to managing node.js assets, we will still have all the io.js assets (domain, twitter, etc) and I expect the website and evangelism teams to find something fun to do with them. I doubt that we'll just delete them or forget they exist :)
