### ISSUE TITLE
Transition dev-policy repo to nodejs organization

### ISSUE THREAD

**Issue by jasnell** [jasnell/dev-policy#72]
Once the io.js organization transition happens, ownership of this repo will be transferred to the nodejs organization.

**Comment by Fishrock123** [comment]
The nodejs org is now up. :)

**Comment by boopathi** [comment]
https://github.com/nodejs

**Comment by jasnell** [comment]
Transfered!

**Comment by Fishrock123** [comment]
:+1: Can either @jasnell or @mikeal put me on some sort of convergence team with permissions to this repo and the convergence one?

**Comment by jasnell** [comment]
@Fishrock123 ... done... the convergence repo is going to take a bit more effort... https://github.com/jasnell/node.js-convergence/issues/8#issuecomment-102465836

**Comment by ChALkeR** [comment]
The dev-policy link in the https://github.com/nodejs/node description should be updated.
