### ISSUE TITLE
Address floating patches

### ISSUE THREAD

**Issue by Fishrock123** [jasnell/dev-policy#73]
For v8 patches, io.js requires them to be upstreamed to v8 first. That being said, I don't know if it's actually written anywhere. cc @bnoordhuis

**Comment by bnoordhuis** [comment]
It's in CONTRIBUTING.md:

> io.js has several bundled dependencies in the _deps/_ and the _tools/_
> directories that are not part of the project proper.  Any changes to files
> in those directories or its subdirectories should be sent to their respective
> projects.  Do not send your patch to us, we cannot accept it.
