### ISSUE TITLE
Clarification on inherited, semver-minor changes

### ISSUE THREAD

**Issue by brendanashworth** [jasnell/dev-policy#76]
I'd like to seek clarification based on semver versioning. For documented API objects (which are inheritable), it is unclear whether typically semver-minor additions on the prototype (https://github.com/nodejs/io.js/commit/b2e00e38dcac23cf564636e8fad880829489286c, https://github.com/nodejs/io.js/commit/e11fc67225821c76d35a483690b952b01f1f7c67) - which would affect inheriting objects - are always semver-minor and not semver-major.

In practice, this seems to be only according to the "popularity of inheritance" on the object in question. It doesn't seem to make sense to base semver decisions on just that, and I'd like to seek for clarification: can these changes be introduced in non-major releases?

See https://github.com/nodejs/io.js/issues/734 for background discussion.

**Comment by jasnell** [comment]
Others on the @nodejs/tsc may want to weigh in on this, but from my perspective, we cannot necessarily gate our versioning on how others might extend the core objects. We simply have no reasonable way of knowing which API additions might conflict with others. (Perhaps once @chrisdickinson has his static analysis of all npm modules we'll have a better sense of this ;-) ...). In practice, however, you are right, we ought to be very careful about adding API to prototypes.

**Comment by trevnorris** [comment]
After lengthy discussion in our TSC meeting that was the basic consensus. @chrisdickinson commented about creating a tool that can look through existing npm modules for specific internal changes, but that won't be immediately available.

It is not a happy place to be, but at the same time we don't want to break "large" (up for debate about how many that actually is) portions of the community with any change. Regardless of whether it is internal or not.

**Comment by brendanashworth** [comment]
Was this the latest TSC meeting? Are there notes?

**Comment by trevnorris** [comment]
This was at least several weeks ago. Don't precisely remember.

@chrisdickinson IIRC we had a brief discussion afterwards about this. You remember what week the meeting was when this was discussed?

**Comment by brendanashworth** [comment]
The only thing that this held up has landed: https://github.com/nodejs/node/commit/8f58fb92fff904a6ca58fd0df9ee5a1816e5b84e, so I'm not sure if that'll create a precedent or we want to go somewhere else with this.. I'll leave it open for now though.
